(cl:in-package poppy_torso_control-srv)
(cl:export '(GROUP-VAL
          GROUP
          RAND_START-VAL
          RAND_START
          CURRENT_START-VAL
          CURRENT_START
          START_POS-VAL
          START_POS
          RAND_TARGET-VAL
          RAND_TARGET
          TARGET_POS-VAL
          TARGET_POS
          EXECUTE-VAL
          EXECUTE
          WAIT-VAL
          WAIT
          RET_PLAN-VAL
          RET_PLAN
          RET_FPS-VAL
          RET_FPS
          ERROR-VAL
          ERROR
          START_POS-VAL
          START_POS
          TARGET_POS-VAL
          TARGET_POS
          PLANS-VAL
          PLANS
))