// Generated by gencpp from file poppy_torso_control/CollisionDistance.msg
// DO NOT EDIT!


#ifndef POPPY_TORSO_CONTROL_MESSAGE_COLLISIONDISTANCE_H
#define POPPY_TORSO_CONTROL_MESSAGE_COLLISIONDISTANCE_H

#include <ros/service_traits.h>


#include <poppy_torso_control/CollisionDistanceRequest.h>
#include <poppy_torso_control/CollisionDistanceResponse.h>


namespace poppy_torso_control
{

struct CollisionDistance
{

typedef CollisionDistanceRequest Request;
typedef CollisionDistanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CollisionDistance
} // namespace poppy_torso_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::poppy_torso_control::CollisionDistance > {
  static const char* value()
  {
    return "c3379f95c70098db0befc78cb72e972b";
  }

  static const char* value(const ::poppy_torso_control::CollisionDistance&) { return value(); }
};

template<>
struct DataType< ::poppy_torso_control::CollisionDistance > {
  static const char* value()
  {
    return "poppy_torso_control/CollisionDistance";
  }

  static const char* value(const ::poppy_torso_control::CollisionDistance&) { return value(); }
};


// service_traits::MD5Sum< ::poppy_torso_control::CollisionDistanceRequest> should match 
// service_traits::MD5Sum< ::poppy_torso_control::CollisionDistance > 
template<>
struct MD5Sum< ::poppy_torso_control::CollisionDistanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::poppy_torso_control::CollisionDistance >::value();
  }
  static const char* value(const ::poppy_torso_control::CollisionDistanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::poppy_torso_control::CollisionDistanceRequest> should match 
// service_traits::DataType< ::poppy_torso_control::CollisionDistance > 
template<>
struct DataType< ::poppy_torso_control::CollisionDistanceRequest>
{
  static const char* value()
  {
    return DataType< ::poppy_torso_control::CollisionDistance >::value();
  }
  static const char* value(const ::poppy_torso_control::CollisionDistanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::poppy_torso_control::CollisionDistanceResponse> should match 
// service_traits::MD5Sum< ::poppy_torso_control::CollisionDistance > 
template<>
struct MD5Sum< ::poppy_torso_control::CollisionDistanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::poppy_torso_control::CollisionDistance >::value();
  }
  static const char* value(const ::poppy_torso_control::CollisionDistanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::poppy_torso_control::CollisionDistanceResponse> should match 
// service_traits::DataType< ::poppy_torso_control::CollisionDistance > 
template<>
struct DataType< ::poppy_torso_control::CollisionDistanceResponse>
{
  static const char* value()
  {
    return DataType< ::poppy_torso_control::CollisionDistance >::value();
  }
  static const char* value(const ::poppy_torso_control::CollisionDistanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POPPY_TORSO_CONTROL_MESSAGE_COLLISIONDISTANCE_H
