// Generated by gencpp from file poppy_torso_control/CollisionDistanceResponse.msg
// DO NOT EDIT!


#ifndef POPPY_TORSO_CONTROL_MESSAGE_COLLISIONDISTANCERESPONSE_H
#define POPPY_TORSO_CONTROL_MESSAGE_COLLISIONDISTANCERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace poppy_torso_control
{
template <class ContainerAllocator>
struct CollisionDistanceResponse_
{
  typedef CollisionDistanceResponse_<ContainerAllocator> Type;

  CollisionDistanceResponse_()
    : distance(0.0)
    , collision(false)  {
    }
  CollisionDistanceResponse_(const ContainerAllocator& _alloc)
    : distance(0.0)
    , collision(false)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;

   typedef uint8_t _collision_type;
  _collision_type collision;





  typedef boost::shared_ptr< ::poppy_torso_control::CollisionDistanceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poppy_torso_control::CollisionDistanceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CollisionDistanceResponse_

typedef ::poppy_torso_control::CollisionDistanceResponse_<std::allocator<void> > CollisionDistanceResponse;

typedef boost::shared_ptr< ::poppy_torso_control::CollisionDistanceResponse > CollisionDistanceResponsePtr;
typedef boost::shared_ptr< ::poppy_torso_control::CollisionDistanceResponse const> CollisionDistanceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poppy_torso_control::CollisionDistanceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poppy_torso_control::CollisionDistanceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace poppy_torso_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'poppy_torso_control': ['/tf/user/ros/poppy_ws/src/poppy_ros/poppy_torso_control/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::poppy_torso_control::CollisionDistanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poppy_torso_control::CollisionDistanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poppy_torso_control::CollisionDistanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poppy_torso_control::CollisionDistanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poppy_torso_control::CollisionDistanceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poppy_torso_control::CollisionDistanceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poppy_torso_control::CollisionDistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d40d5fc4810aa1ed4a9bb475d7d7dd20";
  }

  static const char* value(const ::poppy_torso_control::CollisionDistanceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd40d5fc4810aa1edULL;
  static const uint64_t static_value2 = 0x4a9bb475d7d7dd20ULL;
};

template<class ContainerAllocator>
struct DataType< ::poppy_torso_control::CollisionDistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poppy_torso_control/CollisionDistanceResponse";
  }

  static const char* value(const ::poppy_torso_control::CollisionDistanceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poppy_torso_control::CollisionDistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32         distance\n"
"bool            collision\n"
;
  }

  static const char* value(const ::poppy_torso_control::CollisionDistanceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poppy_torso_control::CollisionDistanceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.collision);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CollisionDistanceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poppy_torso_control::CollisionDistanceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poppy_torso_control::CollisionDistanceResponse_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "collision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.collision);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POPPY_TORSO_CONTROL_MESSAGE_COLLISIONDISTANCERESPONSE_H
