// Generated by gencpp from file poppy_torso_control/ForwardKinematics.msg
// DO NOT EDIT!


#ifndef POPPY_TORSO_CONTROL_MESSAGE_FORWARDKINEMATICS_H
#define POPPY_TORSO_CONTROL_MESSAGE_FORWARDKINEMATICS_H

#include <ros/service_traits.h>


#include <poppy_torso_control/ForwardKinematicsRequest.h>
#include <poppy_torso_control/ForwardKinematicsResponse.h>


namespace poppy_torso_control
{

struct ForwardKinematics
{

typedef ForwardKinematicsRequest Request;
typedef ForwardKinematicsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ForwardKinematics
} // namespace poppy_torso_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::poppy_torso_control::ForwardKinematics > {
  static const char* value()
  {
    return "fd29b61d63688aceaae9b2f12b8a16ee";
  }

  static const char* value(const ::poppy_torso_control::ForwardKinematics&) { return value(); }
};

template<>
struct DataType< ::poppy_torso_control::ForwardKinematics > {
  static const char* value()
  {
    return "poppy_torso_control/ForwardKinematics";
  }

  static const char* value(const ::poppy_torso_control::ForwardKinematics&) { return value(); }
};


// service_traits::MD5Sum< ::poppy_torso_control::ForwardKinematicsRequest> should match 
// service_traits::MD5Sum< ::poppy_torso_control::ForwardKinematics > 
template<>
struct MD5Sum< ::poppy_torso_control::ForwardKinematicsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::poppy_torso_control::ForwardKinematics >::value();
  }
  static const char* value(const ::poppy_torso_control::ForwardKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::poppy_torso_control::ForwardKinematicsRequest> should match 
// service_traits::DataType< ::poppy_torso_control::ForwardKinematics > 
template<>
struct DataType< ::poppy_torso_control::ForwardKinematicsRequest>
{
  static const char* value()
  {
    return DataType< ::poppy_torso_control::ForwardKinematics >::value();
  }
  static const char* value(const ::poppy_torso_control::ForwardKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::poppy_torso_control::ForwardKinematicsResponse> should match 
// service_traits::MD5Sum< ::poppy_torso_control::ForwardKinematics > 
template<>
struct MD5Sum< ::poppy_torso_control::ForwardKinematicsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::poppy_torso_control::ForwardKinematics >::value();
  }
  static const char* value(const ::poppy_torso_control::ForwardKinematicsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::poppy_torso_control::ForwardKinematicsResponse> should match 
// service_traits::DataType< ::poppy_torso_control::ForwardKinematics > 
template<>
struct DataType< ::poppy_torso_control::ForwardKinematicsResponse>
{
  static const char* value()
  {
    return DataType< ::poppy_torso_control::ForwardKinematics >::value();
  }
  static const char* value(const ::poppy_torso_control::ForwardKinematicsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POPPY_TORSO_CONTROL_MESSAGE_FORWARDKINEMATICS_H
