// Generated by gencpp from file poppy_torso_control/GetEndEffectorPosRequest.msg
// DO NOT EDIT!


#ifndef POPPY_TORSO_CONTROL_MESSAGE_GETENDEFFECTORPOSREQUEST_H
#define POPPY_TORSO_CONTROL_MESSAGE_GETENDEFFECTORPOSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace poppy_torso_control
{
template <class ContainerAllocator>
struct GetEndEffectorPosRequest_
{
  typedef GetEndEffectorPosRequest_<ContainerAllocator> Type;

  GetEndEffectorPosRequest_()
    : group()  {
    }
  GetEndEffectorPosRequest_(const ContainerAllocator& _alloc)
    : group(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _group_type;
  _group_type group;





  typedef boost::shared_ptr< ::poppy_torso_control::GetEndEffectorPosRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poppy_torso_control::GetEndEffectorPosRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetEndEffectorPosRequest_

typedef ::poppy_torso_control::GetEndEffectorPosRequest_<std::allocator<void> > GetEndEffectorPosRequest;

typedef boost::shared_ptr< ::poppy_torso_control::GetEndEffectorPosRequest > GetEndEffectorPosRequestPtr;
typedef boost::shared_ptr< ::poppy_torso_control::GetEndEffectorPosRequest const> GetEndEffectorPosRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poppy_torso_control::GetEndEffectorPosRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poppy_torso_control::GetEndEffectorPosRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace poppy_torso_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'poppy_torso_control': ['/tf/user/ros/poppy_ws/src/poppy_ros/poppy_torso_control/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::poppy_torso_control::GetEndEffectorPosRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poppy_torso_control::GetEndEffectorPosRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poppy_torso_control::GetEndEffectorPosRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poppy_torso_control::GetEndEffectorPosRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poppy_torso_control::GetEndEffectorPosRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poppy_torso_control::GetEndEffectorPosRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poppy_torso_control::GetEndEffectorPosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "21b6d99e83cb6198d5c1c624c41148a4";
  }

  static const char* value(const ::poppy_torso_control::GetEndEffectorPosRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x21b6d99e83cb6198ULL;
  static const uint64_t static_value2 = 0xd5c1c624c41148a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::poppy_torso_control::GetEndEffectorPosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poppy_torso_control/GetEndEffectorPosRequest";
  }

  static const char* value(const ::poppy_torso_control::GetEndEffectorPosRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poppy_torso_control::GetEndEffectorPosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string group\n"
;
  }

  static const char* value(const ::poppy_torso_control::GetEndEffectorPosRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poppy_torso_control::GetEndEffectorPosRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.group);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetEndEffectorPosRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poppy_torso_control::GetEndEffectorPosRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poppy_torso_control::GetEndEffectorPosRequest_<ContainerAllocator>& v)
  {
    s << indent << "group: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.group);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POPPY_TORSO_CONTROL_MESSAGE_GETENDEFFECTORPOSREQUEST_H
