// Generated by gencpp from file poppy_torso_control/OffsetMovementRequest.msg
// DO NOT EDIT!


#ifndef POPPY_TORSO_CONTROL_MESSAGE_OFFSETMOVEMENTREQUEST_H
#define POPPY_TORSO_CONTROL_MESSAGE_OFFSETMOVEMENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace poppy_torso_control
{
template <class ContainerAllocator>
struct OffsetMovementRequest_
{
  typedef OffsetMovementRequest_<ContainerAllocator> Type;

  OffsetMovementRequest_()
    : group()
    , offset()
    , execute(false)
    , wait(false)  {
    }
  OffsetMovementRequest_(const ContainerAllocator& _alloc)
    : group(_alloc)
    , offset(_alloc)
    , execute(false)
    , wait(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _group_type;
  _group_type group;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _offset_type;
  _offset_type offset;

   typedef uint8_t _execute_type;
  _execute_type execute;

   typedef uint8_t _wait_type;
  _wait_type wait;





  typedef boost::shared_ptr< ::poppy_torso_control::OffsetMovementRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poppy_torso_control::OffsetMovementRequest_<ContainerAllocator> const> ConstPtr;

}; // struct OffsetMovementRequest_

typedef ::poppy_torso_control::OffsetMovementRequest_<std::allocator<void> > OffsetMovementRequest;

typedef boost::shared_ptr< ::poppy_torso_control::OffsetMovementRequest > OffsetMovementRequestPtr;
typedef boost::shared_ptr< ::poppy_torso_control::OffsetMovementRequest const> OffsetMovementRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poppy_torso_control::OffsetMovementRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poppy_torso_control::OffsetMovementRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace poppy_torso_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'poppy_torso_control': ['/tf/user/ros/poppy_ws/src/poppy_ros/poppy_torso_control/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::poppy_torso_control::OffsetMovementRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poppy_torso_control::OffsetMovementRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poppy_torso_control::OffsetMovementRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poppy_torso_control::OffsetMovementRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poppy_torso_control::OffsetMovementRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poppy_torso_control::OffsetMovementRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poppy_torso_control::OffsetMovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "96dd0ed95f53e9dfc5f7e996477684cf";
  }

  static const char* value(const ::poppy_torso_control::OffsetMovementRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x96dd0ed95f53e9dfULL;
  static const uint64_t static_value2 = 0xc5f7e996477684cfULL;
};

template<class ContainerAllocator>
struct DataType< ::poppy_torso_control::OffsetMovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poppy_torso_control/OffsetMovementRequest";
  }

  static const char* value(const ::poppy_torso_control::OffsetMovementRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poppy_torso_control::OffsetMovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string          group\n"
"float32[]       offset\n"
"bool            execute\n"
"bool            wait\n"
;
  }

  static const char* value(const ::poppy_torso_control::OffsetMovementRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poppy_torso_control::OffsetMovementRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.group);
      stream.next(m.offset);
      stream.next(m.execute);
      stream.next(m.wait);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OffsetMovementRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poppy_torso_control::OffsetMovementRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poppy_torso_control::OffsetMovementRequest_<ContainerAllocator>& v)
  {
    s << indent << "group: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.group);
    s << indent << "offset[]" << std::endl;
    for (size_t i = 0; i < v.offset.size(); ++i)
    {
      s << indent << "  offset[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.offset[i]);
    }
    s << indent << "execute: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.execute);
    s << indent << "wait: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wait);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POPPY_TORSO_CONTROL_MESSAGE_OFFSETMOVEMENTREQUEST_H
