// Generated by gencpp from file poppy_torso_control/PlanMovementRequest.msg
// DO NOT EDIT!


#ifndef POPPY_TORSO_CONTROL_MESSAGE_PLANMOVEMENTREQUEST_H
#define POPPY_TORSO_CONTROL_MESSAGE_PLANMOVEMENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace poppy_torso_control
{
template <class ContainerAllocator>
struct PlanMovementRequest_
{
  typedef PlanMovementRequest_<ContainerAllocator> Type;

  PlanMovementRequest_()
    : group()
    , rand_start(false)
    , current_start(false)
    , start_pos()
    , rand_target(false)
    , target_pos()
    , execute(false)
    , wait(false)
    , ret_plan(false)
    , ret_fps(0)  {
    }
  PlanMovementRequest_(const ContainerAllocator& _alloc)
    : group(_alloc)
    , rand_start(false)
    , current_start(false)
    , start_pos(_alloc)
    , rand_target(false)
    , target_pos(_alloc)
    , execute(false)
    , wait(false)
    , ret_plan(false)
    , ret_fps(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _group_type;
  _group_type group;

   typedef uint8_t _rand_start_type;
  _rand_start_type rand_start;

   typedef uint8_t _current_start_type;
  _current_start_type current_start;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _start_pos_type;
  _start_pos_type start_pos;

   typedef uint8_t _rand_target_type;
  _rand_target_type rand_target;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _target_pos_type;
  _target_pos_type target_pos;

   typedef uint8_t _execute_type;
  _execute_type execute;

   typedef uint8_t _wait_type;
  _wait_type wait;

   typedef uint8_t _ret_plan_type;
  _ret_plan_type ret_plan;

   typedef int8_t _ret_fps_type;
  _ret_fps_type ret_fps;





  typedef boost::shared_ptr< ::poppy_torso_control::PlanMovementRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poppy_torso_control::PlanMovementRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlanMovementRequest_

typedef ::poppy_torso_control::PlanMovementRequest_<std::allocator<void> > PlanMovementRequest;

typedef boost::shared_ptr< ::poppy_torso_control::PlanMovementRequest > PlanMovementRequestPtr;
typedef boost::shared_ptr< ::poppy_torso_control::PlanMovementRequest const> PlanMovementRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poppy_torso_control::PlanMovementRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poppy_torso_control::PlanMovementRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace poppy_torso_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'poppy_torso_control': ['/tf/user/ros/poppy_ws/src/poppy_ros/poppy_torso_control/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::poppy_torso_control::PlanMovementRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poppy_torso_control::PlanMovementRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poppy_torso_control::PlanMovementRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poppy_torso_control::PlanMovementRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poppy_torso_control::PlanMovementRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poppy_torso_control::PlanMovementRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poppy_torso_control::PlanMovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba10917eee5925fa4fe634f7f6f5780b";
  }

  static const char* value(const ::poppy_torso_control::PlanMovementRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba10917eee5925faULL;
  static const uint64_t static_value2 = 0x4fe634f7f6f5780bULL;
};

template<class ContainerAllocator>
struct DataType< ::poppy_torso_control::PlanMovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poppy_torso_control/PlanMovementRequest";
  }

  static const char* value(const ::poppy_torso_control::PlanMovementRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poppy_torso_control::PlanMovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string          group\n"
"bool            rand_start\n"
"bool            current_start\n"
"float32[]       start_pos\n"
"bool            rand_target\n"
"float32[]       target_pos\n"
"bool            execute\n"
"bool            wait\n"
"bool            ret_plan\n"
"int8            ret_fps\n"
;
  }

  static const char* value(const ::poppy_torso_control::PlanMovementRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poppy_torso_control::PlanMovementRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.group);
      stream.next(m.rand_start);
      stream.next(m.current_start);
      stream.next(m.start_pos);
      stream.next(m.rand_target);
      stream.next(m.target_pos);
      stream.next(m.execute);
      stream.next(m.wait);
      stream.next(m.ret_plan);
      stream.next(m.ret_fps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanMovementRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poppy_torso_control::PlanMovementRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poppy_torso_control::PlanMovementRequest_<ContainerAllocator>& v)
  {
    s << indent << "group: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.group);
    s << indent << "rand_start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rand_start);
    s << indent << "current_start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.current_start);
    s << indent << "start_pos[]" << std::endl;
    for (size_t i = 0; i < v.start_pos.size(); ++i)
    {
      s << indent << "  start_pos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.start_pos[i]);
    }
    s << indent << "rand_target: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rand_target);
    s << indent << "target_pos[]" << std::endl;
    for (size_t i = 0; i < v.target_pos.size(); ++i)
    {
      s << indent << "  target_pos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.target_pos[i]);
    }
    s << indent << "execute: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.execute);
    s << indent << "wait: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wait);
    s << indent << "ret_plan: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ret_plan);
    s << indent << "ret_fps: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ret_fps);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POPPY_TORSO_CONTROL_MESSAGE_PLANMOVEMENTREQUEST_H
