// Generated by gencpp from file poppy_torso_control/PlanMovement.msg
// DO NOT EDIT!


#ifndef POPPY_TORSO_CONTROL_MESSAGE_PLANMOVEMENT_H
#define POPPY_TORSO_CONTROL_MESSAGE_PLANMOVEMENT_H

#include <ros/service_traits.h>


#include <poppy_torso_control/PlanMovementRequest.h>
#include <poppy_torso_control/PlanMovementResponse.h>


namespace poppy_torso_control
{

struct PlanMovement
{

typedef PlanMovementRequest Request;
typedef PlanMovementResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanMovement
} // namespace poppy_torso_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::poppy_torso_control::PlanMovement > {
  static const char* value()
  {
    return "739716dc3ed3bb73b035e54b77eee141";
  }

  static const char* value(const ::poppy_torso_control::PlanMovement&) { return value(); }
};

template<>
struct DataType< ::poppy_torso_control::PlanMovement > {
  static const char* value()
  {
    return "poppy_torso_control/PlanMovement";
  }

  static const char* value(const ::poppy_torso_control::PlanMovement&) { return value(); }
};


// service_traits::MD5Sum< ::poppy_torso_control::PlanMovementRequest> should match 
// service_traits::MD5Sum< ::poppy_torso_control::PlanMovement > 
template<>
struct MD5Sum< ::poppy_torso_control::PlanMovementRequest>
{
  static const char* value()
  {
    return MD5Sum< ::poppy_torso_control::PlanMovement >::value();
  }
  static const char* value(const ::poppy_torso_control::PlanMovementRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::poppy_torso_control::PlanMovementRequest> should match 
// service_traits::DataType< ::poppy_torso_control::PlanMovement > 
template<>
struct DataType< ::poppy_torso_control::PlanMovementRequest>
{
  static const char* value()
  {
    return DataType< ::poppy_torso_control::PlanMovement >::value();
  }
  static const char* value(const ::poppy_torso_control::PlanMovementRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::poppy_torso_control::PlanMovementResponse> should match 
// service_traits::MD5Sum< ::poppy_torso_control::PlanMovement > 
template<>
struct MD5Sum< ::poppy_torso_control::PlanMovementResponse>
{
  static const char* value()
  {
    return MD5Sum< ::poppy_torso_control::PlanMovement >::value();
  }
  static const char* value(const ::poppy_torso_control::PlanMovementResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::poppy_torso_control::PlanMovementResponse> should match 
// service_traits::DataType< ::poppy_torso_control::PlanMovement > 
template<>
struct DataType< ::poppy_torso_control::PlanMovementResponse>
{
  static const char* value()
  {
    return DataType< ::poppy_torso_control::PlanMovement >::value();
  }
  static const char* value(const ::poppy_torso_control::PlanMovementResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POPPY_TORSO_CONTROL_MESSAGE_PLANMOVEMENT_H
